# -*- coding: utf-8 -*-
"""inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18n7yGlAHn1MBwp6K7Xh_PCA_DbTGPEiH
"""

# backend/inference.py
import joblib
import qml_core   # must be importable — same file as used above, e.g. backend/qml_core.py

bundle = joblib.load("models/hybrid_qml_v1.pkl")

scaler       = bundle["scaler"]
pca          = bundle["pca"]
angle_scaler = bundle["angle_scaler"]
hybrid_model = bundle["hybrid_model"]
feature_names = bundle["feature_names"]

def predict(raw_features_df):
    x_raw = raw_features_df[feature_names]
    x_c = scaler.transform(x_raw)
    x_q = angle_scaler.transform(pca.transform(x_c))
    prob = hybrid_model.predict_proba(x_c, x_q)[0]
    return float(prob)